name: '[lib] Publish @kenju/gdrive-permissions-codify'
on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '10'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@kenju'
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
